version: '3.8'
services:
  # Django application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: nasalane/django-app:1.0 
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
      - redis 
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=people
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=awa

  # PostgreSQL database
  db:
    image: nasalane/postgres:15.4
    user: postgres
    environment:
      POSTGRES_DB: people
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: awa

  # Redis service 
  redis:
    image: nasalane/redis:alpine

