apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django-app
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app                 
        image: nasalane/django-app:1.0                     
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_DB_HOST
          valueFrom: 
            configMapKeyRef:
              name: postgres-configmap
              key: database_url
        - name: DJANGO_DB_PORT
          value: "5432"
        - name: DJANGO_DB_USER
          valueFrom: 
            secretKeyRef:
              name: django-app-secret
              key: postgres-db-user
        - name: DJANGO_DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: django-app-secret
              key: postgres-db-password
        - name: REDIS_HOST
          valueFrom: 
            configMapKeyRef:
              name: redis-configmap
              key: redis-url


                 