apiVersion: v1
kind: Secret
metadata:
  name: django-app-secret
  annotations:
    argocd.argoproj.io/sync-wave: "3"
type: Opaque
data:
  postgres-db-host: ZGI=
  postgres-db-port: NTQzMg==
  postgres-db-name: cGVvcGxl
  postgres-db-user: cG9zdGdyZXM=
  postgres-db-password: YXdh

