apiVersion: v1
kind: Service
metadata:
  name: django-app-service
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  selector:
    app: django-app
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 8000                  
      targetPort: 8000
      nodePort: 30000    