apiVersion: v1
kind: Service
metadata:
  name: redis
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app: redis-app 
  ports:
    - protocol: TCP
      port: 6379                  
      targetPort: 6379   