name: DevOps Project

on: 
  push:
    branches:  [main]
  pull_request:
    branches: [main]
jobs:
  build-ci:
    runs-on:  ubuntu-latest 
    container: python:3.11.4-bullseye
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies 
      run: pip install -r requirements.txt
    
    - name: Check the formatting
      run: black . --check

    - name: Check the linting
      run: ruff check .

    - name: Run the tests
      run: docker-compose exec web python manage.py test
        
    - name: Setup Docker
      run: |
        docker --version
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build the Docker Compose stack
      run: docker-compose build

    - name: Push the Docker Compose stack to Docker Hub
      run: docker-compose push
