name: DevOps Project

on: 
  push:
    branches:  [main]
  pull_request:
    branches: [main]
jobs:
  build-ci:
    runs-on: ubuntu-latest 
    services:
      postgres:
        image: postgres:15.4
        env:
          POSTGRES_DB: people        
          POSTGRES_PASSWORD: awa
          POSTGRES_USER: postgres
        ports:
          - 5432:5432

      redis:
        image: redis:alpine
        ports:
          - 6379:6379
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies 
      run: pip install -r requirements.txt
    
    - name: Check the formatting
      run: black . --check

    - name: Check the linting
      run: ruff check .
  
    - name: Apply Migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate

    - name: Run Django Tests
      run: python manage.py test

    - name: Setup Docker
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build the Docker Compose stack
      run: |
        docker build nasalane/devops_project

    - name: Push the Docker Compose stack to Docker Hub
      run: docker push nasalane/devops_project