name: DevOps Project

on: 
  push:
    branches:  [main]
  pull_request:
    branches: [main]
jobs:
  build-ci:
    runs-on:  ubuntu-latest 
    container: python:3.11.4-bullseye
    services:
      postgres:
        image: postgres:15.4
        env:
          POSTGRES_DB: people        
          POSTGRES_PASSWORD: awa
          POSTGRES_USER: postgres
          POSTGRES_HOST: db
        ports:
          - 5432:5432
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies 
      run: pip install -r requirements.txt
    
    - name: Check the formatting
      run: black . --check

    - name: Check the linting
      run: ruff check .

    - name: Wait for PostgreSQL to be ready
      run: |
        while ! docker exec -i postgres psql -U postgres -c "SELECT 1" > /dev/null 2>&1; do
            echo "Waiting for PostgreSQL to start..."
            sleep 5
        done

    - name: Apply Migrations
      run: docker-compose exec web python manage.py migrate

    - name: Run Django Tests
      run: docker-compose exec web python manage.py test

    - name: Clean up Docker Compose
      run: docker-compose down

    - name: Setup Docker
      run: |
        docker --version
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build the Docker Compose stack
      run: |
        docker-compose build
        docker-compose up

    - name: Push the Docker Compose stack to Docker Hub
      run: docker-compose push