name: Python package

on: 
  push:
    branches:  [main]
  pull_request:
    branches: [main]
jobs:
  build-ci:
    runs-on:  ubuntu-latest 
    container: python:3.11.4-bullseye
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies 
      run: pip install -r requirements.txt
    
    - name: Check the formatting
      run: black . --check

    - name: Check the linting
      run: ruff check .

    - name: Run the tests
      run: python manage.py test
        
    - name: Build Docker image
      run: docker build -t devops-project:latest . 
      
    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Push Docker image to Docker Hub
      run: |
        docker tag devops-project:latest nasalane/devops-project:latest
        docker push nasalane/devops-project:latest
      

